### ISSUE TITLE
Allow finding common makefiles at top of the workspace

### ISSUE THREAD

**Issue by jayvdb** [sagiegurari/cargo-make#1175]
### Feature Description

Context is https://github.com/sagiegurari/cargo-make/discussions/1163

A workspace member `Makefile.toml` should be able to easily include (extend) common tasks/rules/etc from a cargo-make compliant toml  file that can be located from the top of the workspace. 

Currently one needs to do

```toml
extend = [{ path = "../../../makefiles/tools.toml" }]
```

And the number of "../" depends on the level of the workspace member.  This isnt bad, as it is accurate, but it could be improved upon.

### Describe The Solution You'd Like

I suspect that some very basic and rarely modified (and probably should be immutable) cargo-make defined envvars can be set early enough in the process so that this works:

```toml
extend = [{ path = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/makefiles/tools.toml" }]
```

**Comment by sagiegurari** [comment]
@jayvdb pushed a solution in dev branch 0.37.23 and would love if you can check it.
you now have an additional keyword apart of path, relative. it gets 2 optional values: crate, workspace.
to specify that the path provided is relative either to the current crate root or workspace root.
would love your feedback.

you can look at the extends_list.toml example of how to use it

**Comment by jayvdb** [comment]
Note using `relative = "something-else"` doesnt emit any warning that it is invalid.

In all the cases I have, `relative = "workspace"` on that branch isn't working.

I have a "services/" directory under the workspace root.  It has no files in that directory - only sub-directories for each workspace member.

I have other cases where the workspace member is under `x/y/z/workspace_member_crate_here`.  None of `x`, `y` or `z` have a `Cargo.toml` or `Makefile.toml` - they are only structural.

**Comment by jayvdb** [comment]
`services/serviceA/Makefile.toml`:
```toml
extend = [{ path = "makefiles/tools.toml", relative = "workspace" }]
```
results in
```
> cargo make -l debug
[cargo-make] INFO - cargo make 0.37.22
[cargo-make] ERROR - Descriptor file: "/path/to/workspace_root/services/serviceA/makefiles/tools.toml" not found.
```

The version made me think maybe I had the wrong binary, but seems like this is correct per https://github.com/sagiegurari/cargo-make/commit/8e7ca82fbb0f1be4f267af9fa936fcc8cd93bdbf

**Comment by sagiegurari** [comment]
ya i only bump the version before releasing....

can you share more details like how the workspace looks like, the makefiles, etc so i can reproduce?

**Comment by sagiegurari** [comment]
also if you run with "-v" i'll see some debug logs of if it finds and where it finds the crate/workspace roots. so that might be helpful as well for me

**Comment by sagiegurari** [comment]
just added a 'workspace' example which seems to work well so need that debug info and project structure and makefiles to understand better.

**Comment by sagiegurari** [comment]
is t possible you don't have a Cargo.toml at the workspace root?
did you check the workspace example i pushed? which works

**Comment by sagiegurari** [comment]
@jayvdb adding 2 more things in latest diff
1. "git" as an option. it will search for first top .git folder
2. warning in case an invalid value is defined but still will default to makefile as relative to

**Comment by jayvdb** [comment]
sorry - been very busy

> is t possible you don't have a Cargo.toml at the workspace root?

no.

> did you check the workspace example i pushed?

no. sorry.  I reinstalled using the latest and it still doesnt work in my monorepo.

I am 99% sure it is because we have the structure explained above that has multiple subdirectories.  Your example only has one level.

```
/home/jayvdb/work/project_root/services/serviceA> cargo make -v
...
[cargo-make] VERBOSE - No load script defined.
[cargo-make] VERBOSE - External config parent path: .
[cargo-make] VERBOSE - Loading tasks from file: makefiles/tools.toml base directory: ., relative to: WorkspaceRoot
[cargo-make] VERBOSE - Looking for project root from directory: "/home/jayvdb/work/project_root/services/serviceA"
[cargo-make] VERBOSE - project root: Some(
    "/home/jayvdb/work/project_root/services/serviceA",
)
[cargo-make] VERBOSE - Looking for project root from directory: "/home/jayvdb/work/project_root/services/serviceA/.."
[cargo-make] VERBOSE - Looking for project root from directory: "/home/jayvdb/work/project_root/services/serviceA"
[cargo-make] VERBOSE - workspace root: Some(
    "/home/jayvdb/work/project_root/services/serviceA",
)
[cargo-make] ERROR - Descriptor file: "/home/jayvdb/work/project_root/services/serviceA/makefiles/tools.toml" not found.
[cargo-make] WARN - Build Failed.
```

> "git" as an option. it will search for first top .git folder

this works

> warning in case an invalid value is defined but still will default to makefile as relative to

roger that.

**Comment by sagiegurari** [comment]
@jayvdb released
