### ISSUE TITLE
Workspace members not honored

### ISSUE THREAD

**Issue by Javagedes** [sagiegurari/cargo-make#773]
### Describe The Bug
Workspace members are not honored between Cargo.toml members and the env variable CARGO_MAKE_CRATE_WORKSPACE_MEMBERS.

Per [Cargo Book - Workspaces](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-members-and-exclude-fields):

"All [path dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies) residing in the workspace directory automatically become members."

However, these members are not included in the CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS env variable. 

### To Reproduce

1. Create a workspace that has a member defined within [workspace.dependencies] as a path dependency
2. have a task that prints the contents of CARGO_MAKE_CRATE_WORKSPACE_MEMBERS. Note that it is not included.

### Error Stack

N/A

### Code Sample

```toml
[workspace]
members = ["path/to/my_package1"]  # Only a binary, so added here

[workspace.dependencies]
my_package2 = {path = "path/to/my_package2"} # Has a library that my_package1 uses so added here
```

CARGO_MAKE_CRATE_WORKSPACE_MEMBERS only includes my_package1 even though workspaces will also view my_package2 as a workspace member.

**Comment by Javagedes** [comment]
Please note that there is a simple workaround of adding necessary packages to both members and workspace.dependencies, however it should not be necessary :)

**Comment by sagiegurari** [comment]
thanks for reporting this. i'll check it out. i do remember i support both, so maybe its either or and not and. will check.

**Comment by sagiegurari** [comment]
@Javagedes sorry for late reply. found the issue. I always supported members from dependencies, but the detection was wrong (relative paths issue).
anyhow this is now fixed in a dev branch - 0.36.4 and I would love if you can test it out.

**Comment by sagiegurari** [comment]
published in new version. thanks for reporting.

**Comment by Javagedes** [comment]
Hello @sagiegurari sorry for the slow response. I've tested and It is still not working (Though it could just be me). Here is the current way that I'm testing:

**Makefile.toml**
```toml
[tasks.workspace-members]
script = '''
#!@duckscript
var = get_env CARGO_MAKE_CRATE_WORKSPACE_MEMBERS 
echo ${var}
'''
```

**Cargo.toml (Workspace)**
```toml
[workspace]
members = [
    # Add packages that generate binaries here
    "Platforms/QemuQ35Pkg/RustDriverDxe",
    "Platforms/QemuQ35Pkg/DxeRust",
]

[workspace.dependencies]
# Add packages that generate libraries here
DxeRust = {path = "Platforms/QemuQ35Pkg/DxeRust"}
FvLib = {path = "Platforms/QemuQ35Pkg/Library/FvLib"}
DynamicFrameAllocatorLib = {path = "Platforms/QemuQ35Pkg/Library/DynamicFrameAllocatorLib"}
UefiRustAllocatorLib = {path = "Platforms/QemuQ35Pkg/Library/UefiRustAllocatorLib"}
... removed for brevity. ...
```

**Output from cmd**
```cmd
(venv) PS C:\src\UefiRust> cargo make workspace-members
[cargo-make] INFO - cargo make 0.36.4
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: workspace-members
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: workspace-members
Platforms/QemuQ35Pkg/DxeRust,Platforms/QemuQ35Pkg/RustDriverDxe
[cargo-make] INFO - Build Done in 1.01 seconds.
```

I would expect additional workspace members of `Platforms/QemuQ35Pkg/Library/FvLib`, `Platforms/QemuQ35Pkg/Library/DynamicFrameAllocatorLib`, `Platforms/QemuQ35Pkg/Library/UefiRustAllocatorLib`

By adding them to the workspace manually, it does work as expected, as mentioned before.

**cargo.toml (with workaround)**
```toml
[workspace]
members = [
    # Add packages that generate binaries here
    "Platforms/QemuQ35Pkg/RustDriverDxe",
    "Platforms/QemuQ35Pkg/DxeRust",
    "Platforms/QemuQ35Pkg/Library/FvLib", 
    "Platforms/QemuQ35Pkg/Library/DynamicFrameAllocatorLib",
    "Platforms/QemuQ35Pkg/Library/UefiRustAllocatorLib"
... removed for brevity. ...
]
```

**cmd (with workaround)**
```cmd
(venv) PS C:\src\UefiRust> cargo make workspace-members
[cargo-make] INFO - cargo make 0.36.4
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: workspace-members
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: workspace-members
Platforms/QemuQ35Pkg/DxeRust,Platforms/QemuQ35Pkg/Library/DynamicFrameAllocatorLib,Platforms/QemuQ35Pkg/Library/FvLib,Platforms/QemuQ35Pkg/Library/UefiRustAllocatorLib,Platforms/QemuQ35Pkg/RustDriverDxe
[cargo-make] INFO - Build Done in 0.99 seconds.
```

**Comment by Javagedes** [comment]
@sagiegurari I'll let you decide if you want to re-open this or not :)

**Comment by sagiegurari** [comment]
strange. I'll take another look at it. thanks

**Comment by sagiegurari** [comment]
@Javagedes when you run "cargo metadata" in your workspace root. does it print anything about: FvLib, DynamicFrameAllocatorLib and UefiRustAllocatorLib?

because i pick dependencies and members via cargo-metadata. so maybe its a project setup issue?
if cargo-metadata is able to pick it up, can you setup a small repo so i can reproduce the issue and resolve it? because i've not been able to when things are setup correctly so maybe i'm missing something.

**Comment by Javagedes** [comment]
Hello, yes cargo metadata does pick it up as seen below:

![image](https://user-images.githubusercontent.com/24388509/214377587-44152393-6421-41b5-aae9-4f64b10478e1.png)

I will double check my workspace and see if we've messed it up somehow. and get a small demo repo up for you. It may take me until tomorrow, but I'll get it done :) Thanks for all the help

**Comment by Javagedes** [comment]
@sagiegurari Apologies for taking two weeks when I said I'd do it tomorrow 👎 Here is the example repo:

https://github.com/Javagedes/testrepo

**Comment by sagiegurari** [comment]
@Javagedes thanks, i'll check that out!

**Comment by sagiegurari** [comment]
@Javagedes sorry for late reply, only now had time to look at it.
somehow i missed it, but you setup workspace.dependencies and not top level dependencies and it seems i didn't support it.
So i've now added this support and you can check it in the 0.36.5 development branch.
Thanks a lot of opening the issue, setting up the example repo and all that. Really helped!!!

i'm going to merge the dev branch to master and release a new version shortly.

**Comment by sagiegurari** [comment]
The new cargo-make version is now published.
